sudo: false
cache: pip

addons:
  apt:
    packages:
      - expect-dev  # provides unbuffer utility
      - python-lxml # because pip installation is slow

language: python

python:
  - "2.7"

virtualenv:
  system_site_packages: true

env:
  matrix:
  - VERSION="8.0" LINT_CHECK="1"
  - VERSION="8.0" ODOO_REPO="odoo/odoo" LINT_CHECK="0" DOCS="1"
  - VERSION="8.0" ODOO_REPO="OCA/OCB" LINT_CHECK="0"
  global:
    secure: "HLfds+sQG4JcM52D7b/sTemGvBlVNdfGc4XvJ+py2rx25F4BWojpbOYx44nSiUjBO9U6Eo5kwiK0mWEXoPGg6trQcbiur9kgHrV3+hydlUUKe2/P/mnoP2JAxtu0JBSLxNcG40FdIwEE3Sd0w/ocmxMOp3RmOOVacAY48eWYeh8="

install:
  - git clone https://github.com/OCA/maintainer-quality-tools.git ${HOME}/maintainer-quality-tools
  - export PATH=${HOME}/maintainer-quality-tools/travis:${PATH}
  - travis_install_nightly
  - pip install geojson Shapely sphinx sphinx_bootstrap_theme sphinx-intl odoo-sphinx-autodoc

before_script:
  - if [ -n "${ODOO_REPO}" ] ; then wget --no-check-certificate -O ${HOME}/5620.patch http://patch-diff.githubusercontent.com/raw/odoo/odoo/pull/5620.patch ; fi
  - if [ -n "${ODOO_REPO}" ] ; then IFS="/" read -a REPO <<< "${ODOO_REPO}"; patch -f -d "${HOME}/${REPO[1]}-${VERSION}" -p1 -i ${HOME}/5620.patch ; fi

script:
  - if [ -z "$DOCS" ] ; then travis_run_tests; fi
  - if [ -n "$DOCS" ] ; then ./.travis_build_doc; fi

after_success:
  - if [ -z "$DOCS" ] ; then coveralls; fi
  - if [ -n "$DOCS" ] ; then ./.travis_push_doc; fi
